controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Path home page
home:
    path: /home
    controller: App\Controller\HomeController::index

# Path login page
login:
    path: /login
    controller: App\Controller\LoginController::login

# Path register page
register:
    path: /register
    controller: App\Controller\RegisterController::register


        